name: darkoff
description: "Application for viewing information, tracking progress in game Escape from Tarkov."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: 3.0.3
  freezed_annotation: 3.1.0
  auto_route: 11.1.0
  flutter_dotenv: 6.0.0
  result_dart: 2.1.1
  get_it: 9.2.0
  logger: 2.6.2
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: 3.2.3
  riverpod_generator: 3.0.3
  build_runner: 2.10.4
  json_serializable: 6.11.1
  auto_route_generator: 10.4.0
  flutter_lints: 6.0.0

flutter:

  uses-material-design: true
