name: darkoff
description: "Application for viewing information, tracking progress in game Escape from Tarkov."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.20.2
  i18n_extension: 15.1.1
  shared_preferences: 2.3.3
  flutter_riverpod: 3.0.3
  freezed_annotation: 3.1.0
  auto_route: 11.1.0
  flutter_dotenv: 6.0.0
  result_dart: 2.1.1
  get_it: 9.2.0
  logger: 2.6.2
  cupertino_icons: 1.0.8
  riverpod_annotation: 3.0.3
  graphql: 5.2.3
  json_annotation: 4.9.0
  cached_network_image: 3.4.1
  drift: 2.31.0
  rxdart: 0.28.0
  sqlite3_flutter_libs: 0.5.42
  path_provider: 2.1.4
  path: 1.9.1
  flutter_native_splash: 2.4.7
  flutter_launcher_icons: 0.14.4
  firebase_core: 4.11.0
  firebase_crashlytics: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: 3.2.3
  riverpod_generator: 3.0.3
  build_runner: 2.10.4
  json_serializable: 6.11.1
  auto_route_generator: 10.4.0
  flutter_lints: 6.0.0
  graphql_codegen: 3.0.1
  drift_dev: 2.31.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/categories.json
    - assets/i18n/en.json
    - assets/i18n/ru.json
    - assets/images/splash/
    - assets/images/launcher/
