name: app_localization
description: Localization
publish_to: 'none'
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
