query DarkoffHideout($language: LanguageCode, $gameMode: GameMode) {
  hideoutStations(lang: $language, gameMode: $gameMode) {
    id
    name
    normalizedName
    imageLink
    levels {
      id
      level
      constructionTime
      itemRequirements {
        item {
          id
          name
          shortName
          iconLink
          avg24hPrice
        }
        count
      }
      stationLevelRequirements {
        station {
          id
          name
        }
        level
      }
      traderRequirements {
        trader {
          id
          name
        }
        value
      }
      bonuses {
        type
        name
        value
      }
    }
  }
}
