query DarkoffTasks($language: LanguageCode, $gameMode: GameMode) {
  tasks(lang: $language, gameMode: $gameMode) {
    id
    name
    normalizedName
    kappaRequired
    experience
    minPlayerLevel
    taskImageLink
    wikiLink
    trader {
      name
      normalizedName
      imageLink
    }
    map {
      name
    }
    objectives {
      id
      type
      description
      optional
    }
    taskRequirements {
      task {
        id
        name
      }
      status
    }
    finishRewards {
      traderStanding {
        trader {
          name
        }
        standing
      }
      items {
        item {
          id
          name
          shortName
          iconLink
          avg24hPrice
        }
        count
      }
    }
  }
}
